# Generated by Django 4.2.6 on 2023-10-29 04:51

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='jobs_image/', verbose_name='Фотография')),
                ('title', models.CharField(max_length=255, verbose_name='Название ваканции')),
                ('descriptions', models.TextField(verbose_name='Описание ваканции')),
                ('responsiblities', ckeditor.fields.RichTextField(verbose_name='Обязанности')),
                ('expectations', ckeditor.fields.RichTextField(verbose_name='Ожидание')),
                ('experience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Опыт')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_category', to='jobs.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Ваканция',
                'verbose_name_plural': 'Ваканции',
            },
        ),
    ]
